# Use an official lightweight web server image (Nginx)
FROM nginx:alpine

# Set the directory where the files will be served from
WORKDIR /app

# Copy the static files to the container
COPY . .

# Expose the port that the Nginx server will run on
EXPOSE 80

#test
