name: Build and Push Docker Image On Merge

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      api: ${{ steps.filter.outputs.api }}
      widget: ${{ steps.filter.outputs.widget }}
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            api:
              - 'api/**'
            widget:
              - 'widget/**'

  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - paths-filter
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hexabot-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hexabot-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hexabot-widget:latest
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
        env:
          DOCKER_AUTH_CONFIG: ${{ needs.docker-setup.outputs.auth_token }}
    strategy:
      matrix:
        context:
          - ./frontend
          - ./api
          - ./widget
        dockerfile:
          - ./frontend/Dockerfile
          - ./api/Dockerfile
          - ./widget/Dockerfile
    if: ${{ needs.paths-filter.outputs.frontend == 'true' || needs.paths-filter.outputs.api == 'true' || needs.paths-filter.outputs.widget == 'true' }}
