name: Build and Push Docker Image On Merge
on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  # paths-filter:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     frontend: ${{ steps.filter.outputs.frontend }}
  #     api: ${{ steps.filter.outputs.api }}
  #     widget: ${{ steps.filter.outputs.widget }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Filter paths
  #       id: filter
  #       uses: dorny/paths-filter@v3
  #       with:
  #         filters: |
  #           frontend:
  #             - 'frontend/**'
  #           api:  
  #             - 'api/**'
  #           widget:
  #             - 'widget/**'

  docker-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code ...
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  frontend-build-and-push:
    runs-on: ubuntu-latest
    # if: ${{ needs['paths-filter'].outputs.frontend == 'true' }}
    needs: docker-setup
    steps:
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hexabot-frontend:latest

  api-build-and-push:
    runs-on: ubuntu-latest
    # if: ${{ needs.paths-filter.outputs.api == 'true' }}
    needs: docker-setup
    steps:
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hexabot-api:latest

  widget-build-and-push:
    runs-on: ubuntu-latest
    # if: ${{ needs.paths-filter.outputs.widget == 'true' }}
    needs: docker-setup
    steps:
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./widget/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hexabot-widget:latest
